version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - 'aws s3 cp s3://manifest-environment-variables/aws-exports.js aws-exports.js'
      - npm install --silent --global expo-cli
      - |-
        if [ -f yarn.lock ]; then
         yarn
        elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
         npm ci
        else
         npm install
        fi
  build:
    commands:
      - 'expo build:web'
artifacts:
  files:
    - '**/*'
  base-directory: 'web-build'
cache:
  paths:
    - node_modules/**/*
    - $(npm root --global)/**/*
