--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/4/2022 12:34:44 PM
-- Server version: 10.5.13
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO manifest.checkin(uid, timestamp, stress_lvl, anxiety_lvl, energy_lvl, improvement, mood) VALUES
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-03-30 01:44:40', 2, 0, 8, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":true,"confused":false,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-03-30 02:18:10', 7, 3, 3, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":true,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-03-30 12:55:58', 5, 5, 5, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":true,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('be1f1c6a-0703-49a5-8fc6-cf6764b048f0', '2022-03-30 22:28:38', 0, 0, 3, '{"stress":false,"anxiety":false,"energy":true}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:11:05', 7, 2, 4, '{"stress":false,"anxiety":true,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":true,"angry":false}'),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:11:40', 5, 5, 5, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:15:14', 5, 8, 5, '{"stress":false,"anxiety":true,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-01 02:25:01', 4, 4, 2, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":true,"confused":false,"sad":false,"angry":false}'),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-01 02:25:25', 5, 5, 5, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-01 16:01:40', 10, 10, 10, '{"stress":true,"anxiety":true,"energy":true}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":true,"angry":true}'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-01 16:08:50', 0, 1, 8, '{"stress":false,"anxiety":true,"energy":false}', '{"joyful":false,"happy":true,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:13:55', 1, 3, 6, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":true,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:25:44', 1, 3, 8, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":true,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:29:22', 1, 1, 5, '{"stress":false,"anxiety":false,"energy":true}', '{"joyful":true,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('aea4f01e-1b8a-48b2-a483-6ad0f0df67cb', '2022-04-03 20:34:50', 8, 7, 2, '{"stress":false,"anxiety":true,"energy":false}', '{"joyful":false,"happy":true,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('aea4f01e-1b8a-48b2-a483-6ad0f0df67cb', '2022-04-03 20:35:16', 5, 1, 5, '{"stress":false,"anxiety":false,"energy":true}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":true}'),
('317d1f4f-210f-4e87-b581-23c55f080a5e', '2022-04-06 04:30:24', 5, 5, 5, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('2167bca8-c8c7-4fd5-81a6-c4e2d81687ac', '2022-04-07 13:09:34', 8, 7, 4, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":true,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-14 03:02:23', 2, 0, 5, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":true,"happy":true,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-16 16:27:10', 5, 5, 5, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":true,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:44:23', 0, 2, 0, '{"stress":false,"anxiety":true,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:53:53', 1, 7, 3, '{"stress":false,"anxiety":true,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":true}'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:54:25', 5, 5, 5, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:54:32', 8, 6, 9, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 13:07:40', 7, 2, 1, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 18:13:10', 0, 0, 5, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('a003a9ab-aa66-4d0a-bf34-681943dc8c83', '2022-04-21 17:21:34', 10, 9, 0, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":true,"confused":false,"sad":false,"angry":false}'),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-21 18:47:03', 8, 5, 4, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":true,"confused":false,"sad":false,"angry":false}'),
('5e4e7f28-d0c5-486f-9f6f-8d63b6483a80', '2022-04-21 21:51:19', 10, 10, 0, '{"stress":true,"anxiety":true,"energy":true}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":true,"angry":true}'),
('d1187230-8150-4a1b-8c32-173a54787ab5', '2022-04-21 22:38:01', 6, 6, 3, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":false,"indifferent":false,"confused":true,"sad":false,"angry":false}'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-25 19:27:02', 0, 1, 9, '{"stress":false,"anxiety":false,"energy":false}', '{"joyful":false,"happy":true,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('d1187230-8150-4a1b-8c32-173a54787ab5', '2022-04-27 22:14:15', 2, 3, 5, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":false,"happy":false,"relaxed":true,"indifferent":false,"confused":false,"sad":false,"angry":false}'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-28 14:40:00', 3, 0, 5, '{"stress":true,"anxiety":false,"energy":false}', '{"joyful":true,"happy":false,"relaxed":false,"indifferent":false,"confused":false,"sad":false,"angry":false}');




INSERT INTO manifest.goals(uid, timestamp, category, name, time, freq, notification, progress, nfHour, nfMin) VALUES
('test', '2022-02-09 07:00:00', 'test', 'test', 0, 0, 'hourly', 5, NULL, NULL),
('b2778a2c-a743-4393-a101-85f31ac73448', '2022-03-30 14:23:42', 'Test', 'Exercise daily', 60, 0, 'daily', 4, NULL, NULL),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-03-30 14:59:54', 'Test', 'Work out more ', 60, 1, 'daily', 3, NULL, NULL),
('be1f1c6a-0703-49a5-8fc6-cf6764b048f0', '2022-03-30 22:31:54', 'Test', 'Study for physics quiz ', 60, 0, 'hourly', 0, NULL, NULL),
('be1f1c6a-0703-49a5-8fc6-cf6764b048f0', '2022-03-30 22:35:42', 'Test', 'Hello', 3005, 10, 'hourly', 1860, NULL, NULL),
('be1f1c6a-0703-49a5-8fc6-cf6764b048f0', '2022-03-30 22:36:02', 'Test', 'Ok', 0, 5, 'hourly', 0, NULL, NULL),
('be1f1c6a-0703-49a5-8fc6-cf6764b048f0', '2022-03-30 22:36:47', 'Test', 'Ok', 0, 5, 'hourly', 0, NULL, NULL),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:23:16', 'Test', '', 0, 0, 'none', 0, NULL, NULL),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:23:20', 'Test', '', 0, 0, 'none', 0, NULL, NULL),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:23:27', 'Test', '', 0, 0, 'none', 0, NULL, NULL),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:32:31', 'Test', 'Hello', 60, 0, 'daily', 42, NULL, NULL),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:23:58', 'Test', '', 0, 0, 'daily', 0, NULL, NULL),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-25 13:58:05', 'Test', 'Finish project update ', 1201, 1, 'hourly', 267, NULL, NULL),
('test', '2022-02-09 07:00:00', 'test', 'test', 0, 0, 'hourly', 5, NULL, NULL),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:14:14', 'Test', 'Present Well', 60, 0, 'hourly', 4, NULL, NULL),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:26:06', 'Test', 'Finish paper', 60, 0, 'hourly', 4, NULL, NULL),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-25 19:27:34', 'Test', 'Fix bugs', 60, 0, 'daily', 15, NULL, NULL),
('2167bca8-c8c7-4fd5-81a6-c4e2d81687ac', '2022-04-07 13:14:19', 'Test', 'complete homework', 600, 5, 'daily', 23, NULL, NULL),
('2167bca8-c8c7-4fd5-81a6-c4e2d81687ac', '2022-04-07 13:14:47', 'Test', 'a', 60, 0, 'none', 1, NULL, NULL),
('b71acf9a-3135-455a-a806-325531827094', '2022-04-12 15:18:32', 'Test', 'sleep', 600, 1, 'hourly', 4, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:07', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:09', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:09', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:23', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:23', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:23', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:24', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 21:57:38', 'Test', 'Bb', 0, 0, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 22:09:16', 'Test', 'Ok', 60, 7, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 22:10:34', 'Test', 'Ok', 60, 6, 'none', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 22:15:51', 'Test', 'J', 60, 3, 'daily', 0, NULL, NULL),
('function sub() {    [native code]}', '2022-04-13 22:17:47', 'Test', 'J', 366, 5, 'none', 0, NULL, NULL),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-04-16 17:56:03', 'Test', 'First Goal', 80, 23, 'daily', 60, NULL, NULL),
('aea4f01e-1b8a-48b2-a483-6ad0f0df67cb', '2022-04-20 04:07:44', 'Test', 'Set 12am', 10, 0, 'true', 0, '0', '09'),
('aea4f01e-1b8a-48b2-a483-6ad0f0df67cb', '2022-04-20 04:07:24', 'Test', 'Uiuh', 360, 0, 'true', 0, '0', '08'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:58:32', 'Test', 'Anger manage', 90, 1, 'true', 0, '12', '00'),
('a003a9ab-aa66-4d0a-bf34-681943dc8c83', '2022-04-21 17:26:24', 'Test', 'Test', 90, 51, 'true', 50, '0', '00'),
('d1187230-8150-4a1b-8c32-173a54787ab5', '2022-04-27 22:15:19', 'Test', 'Stuff', 60, 0, 'true', 0, '18', '16'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-28 14:43:29', 'Test', 'Task', 30, 0, 'true', 6, '10', '44'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-28 14:43:51', 'Test', 'New tasn', 0, 5, 'false', 2, '10', '00');


INSERT INTO manifest.journal(uid, timestamp, category, message, title) VALUES
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-03-09 19:51:43', 'none', 'undefined', 'hello world part 2!'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-03-30 00:38:20', 'none', 'I am feelings', 'My Feeling'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-03-30 12:53:31', 'none', 'entry text', 'Test 56'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-03-11 00:06:57', 'blank', 'ooh yah', 'testing'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-03-30 12:55:48', 'blank', 'Goal', 'Cool Beans'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 21:48:24', 'blank', 'Qwe', 'Wee'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 21:49:52', 'blank', '==', 'Hello'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 21:52:16', 'blank', 'Er', 'Werw'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 22:10:52', 'blank', 'Helloooo', 'Hi'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 22:05:47', 'blank', 'Qq', 'Qqqq'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 22:11:03', 'blank', 'Test', 'Test'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 22:12:45', 'blank', 'Again22', 'Again'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-03-29 22:20:31', 'blank', 'Hello', 'Hello'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-03-30 00:14:34', 'blank', 'heyo', 'test'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-03-30 00:38:11', 'blank', 'It be like that like that sometimes ', 'New Journal'),
('be1f1c6a-0703-49a5-8fc6-cf6764b048f0', '2022-03-30 22:23:14', 'blank', 'This experience was quite smooth, and everything worked as expected', 'Maplestory'),
('b34a0c31-02e9-48c5-ae7f-40668088adae', '2022-03-31 18:07:32', 'blank', '', 'Hello~'),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-01 02:15:10', 'blank', 'Was a good day! Very tiring, but feel accomplished. :)', 'Today - 3.31'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 18:06:32', 'blank', 'Hellos', 'Hi'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-01 16:01:57', 'blank', 'Letters', 'Happy thoughts '),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:13:38', 'blank', 'Text here', 'Hello Class!'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:25:30', 'blank', 'Sample text', 'Hello!'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-03 20:29:06', 'blank', 'hello!', 'Presentation'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-05 21:24:18', 'blank', 'Sdf', 'Testing'),
('2167bca8-c8c7-4fd5-81a6-c4e2d81687ac', '2022-04-07 13:08:07', 'blank', 'I am writing text here. Awesome website!', 'Some Title'),
('b71acf9a-3135-455a-a806-325531827094', '2022-04-12 15:19:29', 'blank', 'hhhee', 'hhhe'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:45:03', 'blank', 'Happy thoughts \nAngry music', 'Blank'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 13:01:40', 'blank', 'Entry', 'Heys'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 12:57:49', 'blank', 'My name is', 'Hello'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-21 17:29:49', 'blank', 'Blank be like', 'Another'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 18:07:04', 'blank', 'Edit', 'Ok'),
('a003a9ab-aa66-4d0a-bf34-681943dc8c83', '2022-04-21 17:17:16', 'blank', 'Bdjdjfbdms\n', 'Bdjdnd'),
('a003a9ab-aa66-4d0a-bf34-681943dc8c83', '2022-04-21 17:17:25', 'blank', 'I fucking hate this guy so much, he came into my room today expecting me to test this fucking stupid app. It sucks. End of story.\n', 'Fuck Bryce'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-21 17:29:38', 'blank', 'Hi', 'Hello'),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-25 14:01:31', 'blank', 'Yooooo', 'Yo'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-25 14:40:12', 'blank', 'test', 'test'),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', '2022-04-25 19:26:42', 'blank', '!', 'Hello'),
('d1187230-8150-4a1b-8c32-173a54787ab5', '2022-04-27 22:13:56', 'blank', 'Yo', 'Check '),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-28 14:39:27', 'blank', 'Texts', 'Entry');


INSERT INTO manifest.prompted_entries(uid, timestamp, title, q1, q2, q3, q4, q5) VALUES
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-06 19:58:05', 'Daily', 'Hey', 'asdfa', 'asf', 'asdf', 'asfASD'),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-06 19:57:12', 'Maybe', 'No', 'Maybe', 'Can not use enter', 'Things', 'I am'),
('aad0b095-ba02-4cc2-a4d2-d9106567a87a', '2022-04-16 18:03:01', '', '', '', '', '', 'Yes'),
('2a90e9ed-b960-47cd-80d9-2ee9a6b3c96d', '2022-04-20 12:47:58', 'The crowd or the stage', '', '', '', '', ''),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 13:04:53', 'Hi', 'Thing', '', '', '', ''),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-20 18:01:20', 'Titles', 'No', '', '', '', 'I am'),
('a003a9ab-aa66-4d0a-bf34-681943dc8c83', '2022-04-21 17:18:45', '', 'Bryce', 'Maybe he’s sad and needs company', 'Nothing', '', ''),
('eb4aeaf7-0bf6-417b-bbfb-68159b491f06', '2022-04-25 14:01:46', 'Oh', '', '', '', '', ''),
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', '2022-04-28 14:37:27', 'Hey', '', '', '', '', '');



INSERT INTO manifest.test(id, value) VALUES
(1, 'value'),
(2, 'value');


INSERT INTO manifest.user(uid, points, streak, notifications, friends) VALUES
('userid', 1, 1, '', NULL);


INSERT INTO manifest.user_settings(uid, email, min_stress, min_energy, min_anxiety, friends, pending_invitations, max_stress, max_energy, max_anxiety) VALUES
('0d7336d6-7ae6-40ae-ab47-dda67f10a4f4', 'khusbu0514@gmail.com', NULL, NULL, NULL, NULL, '["patelparadise39@gmail.com"]', NULL, NULL, NULL),
('aea4f01e-1b8a-48b2-a483-6ad0f0df67cb', 'rmathew40@gatech.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('b34a0c31-02e9-48c5-ae7f-40668088adae', 'bacree3@gatech.edu', NULL, NULL, NULL, '[""]', '[""]', NULL, NULL, NULL),
('d1187230-8150-4a1b-8c32-173a54787ab5', 'khusbu0514@gmail.com', NULL, NULL, NULL, '["rmathew40@gatech.edu"]', '["bacree3@gatech.edu","guptaaniruddha27@gmail.com"]', NULL, NULL, NULL),
('e1b1529b-9893-4ff2-ba2a-7ec5d4138484', 'patelparadise39@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('fc8b4f7d-301c-4bd1-a214-ced6a6edd4db', 'bryceacree@gmail.com', NULL, NULL, NULL, '[""]', '["bacree3@gatech.edu"]', NULL, NULL, NULL),
('function sub() {    [native code]}', 'undefined', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);